### ISSUE TITLE
[WIP] New Models

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#229]
# New Models WIP

```yaml

Translation:
  sentence: Sentence
  language: String
  text: String

Pronunciation (django app):
  - Lesson:
     language: String
     level: Int
     sentences: [Sentence]
  
```
