### ISSUE TITLE
[Reviews] Add "tags" to each recording

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#236]
```yaml
Tags:
  proficiency (of what?):
    - novice
    - intermediate
    - advanced
  accents:
    - east:
    - north:
    - south:
    - west:
```
